name: AppMemo
description: Under Construction

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  json_annotation: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.0
  json_serializable: ^0.5.0


flutter:
  uses-material-design: true
